"""add_is_like_to_likes

Revision ID: 05971ccd2ffd
Revises: 9b8ba712ef2e
Create Date: 2026-03-29 15:00:08.956481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05971ccd2ffd'
down_revision: Union[str, None] = '9b8ba712ef2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_like', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'is_like')
    # ### end Alembic commands ###
