"""add_user_id_to_chats

Revision ID: 62d2e65f9e63
Revises: 4faf50e12b8e
Create Date: 2026-03-29 21:04:29.031672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d2e65f9e63'
down_revision: Union[str, None] = '4faf50e12b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'chats', 'tg_users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    # ### end Alembic commands ###
