"""add_likes_and_matches

Revision ID: 9b8ba712ef2e
Revises: 31b76ff2b25e
Create Date: 2026-03-29 14:58:39.097465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8ba712ef2e'
down_revision: Union[str, None] = '31b76ff2b25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('liker_id', sa.Uuid(), nullable=False),
    sa.Column('liked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['liked_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('matched_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('likes')
    # ### end Alembic commands ###
