"""add_rating_referral_user_fields

Revision ID: e1ab28a662b9
Revises: e1b514c3b929
Create Date: 2026-03-29 16:06:38.781727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ab28a662b9'
down_revision: Union[str, None] = 'e1b514c3b929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age_score', sa.Float(), nullable=False),
    sa.Column('gender_score', sa.Float(), nullable=False),
    sa.Column('interests_score', sa.Float(), nullable=False),
    sa.Column('geo_score', sa.Float(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('photos_score', sa.Float(), nullable=False),
    sa.Column('primary_rating', sa.Float(), nullable=False),
    sa.Column('likes_count_score', sa.Float(), nullable=False),
    sa.Column('like_dislike_ratio', sa.Float(), nullable=False),
    sa.Column('match_rate', sa.Float(), nullable=False),
    sa.Column('message_rate', sa.Float(), nullable=False),
    sa.Column('activity_time_score', sa.Float(), nullable=False),
    sa.Column('behavioral_rating', sa.Float(), nullable=False),
    sa.Column('bonus_points', sa.Float(), nullable=False),
    sa.Column('final_rating', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_behavioral_rating'), 'ratings', ['behavioral_rating'], unique=False)
    op.create_index(op.f('ix_ratings_final_rating'), 'ratings', ['final_rating'], unique=False)
    op.create_index(op.f('ix_ratings_primary_rating'), 'ratings', ['primary_rating'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=True)
    op.create_table('referrals',
    sa.Column('referrer_id', sa.Uuid(), nullable=False),
    sa.Column('referred_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.add_column('tg_users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('tg_users', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tg_users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_users', 'is_verified')
    op.drop_column('tg_users', 'is_premium')
    op.drop_column('tg_users', 'last_seen')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_primary_rating'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_final_rating'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_behavioral_rating'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
